#!/bin/bash


# This script is intended to be run when setting up a new unprovisioned image.
# It is *not* executed as part of the day-to-day CI setup process.

set -euxo pipefail

cleanup () {
  set +x
  rm -rf \
    /var/cache/apt/archives/*.deb \
    /var/cache/apt/archives/partial/*.deb \
    /var/cache/apt/*.bin \
    /var/lib/apt/lists/* \
    /var/log/apt/*
}

trap 'cleanup' EXIT

systemctl --quiet disable apt-daily-upgrade.timer apt-daily.timer

apt-get update -o APT::Acquire::Retries=4 -qq \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4 -qq)

packages=$(cat "${BASH_SOURCE%/*}/packages-unprovisioned.txt")
apt-get install --no-install-recommends \
  -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
  ${packages}

# Set the version of Java to match Jenkins.
update-java-alternatives --jre-headless -s \
  java-1.21.0-openjdk-$(dpkg-architecture -qDEB_HOST_ARCH)

groupadd docker
usermod -a -G docker ubuntu
