#!/bin/bash

# Copyright (c) 2020, Massachusetts Institute of Technology.
# Copyright (c) 2020, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'ERROR: This script must be run as root' >&2
  exit 1
fi

if [[ ! -d /media/ephemeral0/ubuntu ]]; then
  mkfs -t ext4 /dev/nvme0n1
  mkdir -p /media/ephemeral0
  mount /dev/nvme0n1 /media/ephemeral0

  dd if=/dev/zero of=/media/ephemeral0/swap bs=1M \
    count="$(grep MemTotal /proc/meminfo | awk '{print int(sqrt($2)/1024+0.5)*1024}')"

  chown root:root /media/ephemeral0/swap
  chmod u=rw,og= /media/ephemeral0/swap
  mkswap /media/ephemeral0/swap
  swapon /media/ephemeral0/swap

  mkdir -p /media/ephemeral0/tmp
  chown root:root /media/ephemeral0/tmp
  chmod a=rwx /media/ephemeral0/tmp

  mkdir -p /media/ephemeral0/ubuntu
  chown ubuntu:ubuntu /media/ephemeral0/ubuntu
  chmod u=rwx,go=rx /media/ephemeral0/ubuntu
fi

echo 'APT::Acquire::Retries "4";' | tee /etc/apt/apt.conf.d/80-acquire-retries

export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
trap 'rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT

apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy
  git \
  openjdk-8-jre-headless \
  openssh-client

update-java-alternatives --jre-headless -s java-1.8.0-openjdk-amd64
