#!/bin/bash

# BSD 3-Clause License
#
# Copyright (c) 2020, Massachusetts Institute of Technology.
# Copyright (c) 2020, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'ERROR: This script must be run as root' >&2
  exit 1
fi

systemctl --quiet disable apt-daily-upgrade.timer apt-daily.timer

if [[ ! -d /media/ephemeral0/ubuntu ]]; then
  # NOTE: each distribution upgrade has resulted in changing the search logic
  # to find the largest disk attached to create /media/ephemeral0/ubuntu.  In
  # this formulation we rely on `lsblk` reporting type `disk` for the desired
  # destination drive, which may not always be true.  Example standard outputs:
  #
  # Focal:
  # $ lsblk
  # NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  # ... loop devices ...
  # nvme1n1     259:0    0 372.5G  0 disk
  # nvme0n1     259:1    0    16G  0 disk
  # └─nvme0n1p1 259:2    0    16G  0 part /
  #
  # Jammy:
  # NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
  # ... loop devices ...
  # nvme0n1      259:0    0     8G  0 disk
  # ├─nvme0n1p1  259:2    0   7.9G  0 part /
  # ├─nvme0n1p14 259:3    0     4M  0 part
  # └─nvme0n1p15 259:4    0   106M  0 part /boot/efi
  # nvme1n1      259:1    0 372.5G  0 disk
  #
  # In both instances we desire `/dev/nvme1n1`, which is the largest disk
  # storage attached.  The pipeline below executes:
  #
  # 1. `lsblk` to query SIZE (in bytes via -b to enable sorting), NAME, and
  #    TYPE, output in key="value" pairs (-P) to make `sed` more reliable.
  # 2. Filter for just the `disk` types using `grep`.
  # 3. Transform remaining `SIZE="size" NAME="name" TYPE="type"` lines into
  #    `size:name` using `sed` to enable sorting on `size` and easy `name`
  #    extraction via `cut`.
  # 4. Numerically sort in reverse the output (`sort -nr`), meaning the largest
  #    `disk` will be the first line, and select the largest (`head -1`).
  # 5. Finally, extract `name` from `size:name` via `cut`, producing a final
  #    result of `/dev/{name}` to create the additional storage on.
  readonly DEV_EPHEMERAL0="/dev/$(lsblk -b -o SIZE,NAME,TYPE -P | grep disk | \
    sed 's/SIZE="\(.*\)" NAME="\(.*\)" TYPE=.*/\1:\2/g' | sort -nr | head -1 | \
    cut -d : -f 2)"

  mkfs -t ext4 "${DEV_EPHEMERAL0}"
  mkdir -p /media/ephemeral0
  mount "${DEV_EPHEMERAL0}" /media/ephemeral0

  dd if=/dev/zero of=/media/ephemeral0/swap bs=1M \
    count="$(grep MemTotal /proc/meminfo | awk '{print int($2/2048)}')"

  chown root:root /media/ephemeral0/swap
  chmod u=rw,og= /media/ephemeral0/swap
  mkswap /media/ephemeral0/swap
  swapon /media/ephemeral0/swap

  mkdir -p /media/ephemeral0/tmp /media/ephemeral0/ubuntu

  chown root:root /media/ephemeral0/tmp
  chmod a=rwx /media/ephemeral0/tmp

  chown ubuntu:ubuntu /media/ephemeral0/ubuntu
  chmod u=rwx,go=rx /media/ephemeral0/ubuntu
fi

# Although `docker` may be installed at a later phase (via `install_prereqs`),
# we need our build user to already be in that group before the login completes
# and therefore need to do this unconditionally.  Previously this was a
# provisioning step, but it is easier to keep it in the init script.  For
# builds that are not using `docker`, this does exactly nothing meaningful.
groupadd docker
usermod -aG docker ubuntu

export DEBIAN_FRONTEND=noninteractive

apt-get update -o APT::Acquire::Retries=4 -qq \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4 -qq)
trap 'set +x; rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*; set -x' EXIT

apt-get install --no-install-recommends -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
  git \
  openjdk-17-jre-headless \
  openssh-client

update-java-alternatives --jre-headless -s java-1.17.0-openjdk-amd64
