#!/bin/bash

set -euxo pipefail

die () {
  echo >&2 "$@"
  exit 1
}

[[ "${EUID}" -eq 0 ]] || die 'This script must be run as root'

if [[ ! -d /media/ephemeral0/ubuntu ]]; then
  # NOTE: Historically, each distribution upgrade has resulted in changing the
  # search logic to find the largest disk attached to create
  # /media/ephemeral0/ubuntu. In this formulation we rely on `lsblk` reporting
  # type `disk` for the desired destination drive, which may not always be
  # true.  Example standard output:
  #
  # Focal:
  # $ lsblk
  # NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  # ... loop devices ...
  # nvme1n1     259:0    0 372.5G  0 disk
  # nvme0n1     259:1    0    16G  0 disk
  # └─nvme0n1p1 259:2    0    16G  0 part /
  #
  # In this instance we desire `/dev/nvme1n1`, which is the largest disk
  # storage attached.  The pipeline below executes:
  #
  # 1. `lsblk` to query SIZE (in bytes via -b to enable sorting), NAME, and
  #    TYPE, output in key="value" pairs (-P) to make `sed` more reliable.
  # 2. Filter for just the `disk` types using `grep`.
  # 3. Transform remaining `SIZE="size" NAME="name" TYPE="type"` lines into
  #    `size:name` using `sed` to enable sorting on `size` and easy `name`
  #    extraction via `cut`.
  # 4. Numerically sort in reverse the output (`sort -nr`), meaning the largest
  #    `disk` will be the first line, and select the largest (`head -1`).
  # 5. Finally, extract `name` from `size:name` via `cut`, producing a final
  #    result of `/dev/{name}` to create the additional storage on.
  readonly DEV_EPHEMERAL0="/dev/$(lsblk -b -o SIZE,NAME,TYPE -P | grep disk | \
    sed 's/SIZE="\(.*\)" NAME="\(.*\)" TYPE=.*/\1:\2/g' | sort -nr | head -1 | \
    cut -d : -f 2)"

  mkfs -t ext4 "${DEV_EPHEMERAL0}"
  mkdir -p /media/ephemeral0
  mount "${DEV_EPHEMERAL0}" /media/ephemeral0

  dd if=/dev/zero of=/media/ephemeral0/swap bs=1M \
    count="$(grep MemTotal /proc/meminfo | awk '{print int($2/2048)}')"

  chown root:root /media/ephemeral0/swap
  chmod u=rw,og= /media/ephemeral0/swap
  mkswap /media/ephemeral0/swap
  swapon /media/ephemeral0/swap

  mkdir -p /media/ephemeral0/tmp /media/ephemeral0/ubuntu

  chown root:root /media/ephemeral0/tmp
  chmod a=rwx /media/ephemeral0/tmp

  chown ubuntu:ubuntu /media/ephemeral0/ubuntu
  chmod u=rwx,go=rx /media/ephemeral0/ubuntu
fi
