#!/bin/bash

# Copyright (c) 2019, Massachusetts Institute of Technology.
# Copyright (c) 2019, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ -z "${WORKSPACE-}" ]]; then
  echo 'ERROR: This script must be run on a Jenkins node' >&2
  exit 1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo 'ERROR: This script must be run as root' >&2
  exit 2
fi

echo 'APT::Acquire::Retries "4";' | tee /etc/apt/apt.conf.d/80-acquire-retries

export DEBIAN_FRONTEND=noninteractive
export PYTHONWARNINGS=ignore::SyntaxWarning

apt-get update -qq
trap 'rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT

apt-get purge --autoremove -o Dpkg::Use-Pty=0 -qy cron unattended-upgrades
rm -rf /var/log/unattended-upgrades

apt-get upgrade -o Dpkg::Options::=--force-confdef \
  -o Dpkg::Options::=--force-confnew -o Dpkg::Use-Pty=0 -qy

apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
  apt-transport-https \
  awscli \
  ca-certificates \
  git \
  gnupg \
  lsb-release \
  ntp \
  openjdk-8-jre-headless \
  wget \
  xvfb

update-java-alternatives --jre-headless -s java-1.8.0-openjdk-amd64

systemctl disable apt-daily.service
systemctl disable apt-daily.timer

cat << 'EOF' > /lib/systemd/system/xvfb.service
[Unit]
After=network.target

[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset

[Install]
WantedBy=multi-user.target
EOF

systemctl --now enable /lib/systemd/system/xvfb.service

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

apt-key adv --fetch-keys \
  https://apt.kitware.com/keys/kitware-archive-latest.asc

echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main" \
  | tee /etc/apt/sources.list.d/kitware.list

apt-get update -qq
apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
  cmake \
  kitware-archive-keyring

apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA

wget -nv -O /tmp/gurobi9.0.2_linux64.tar.gz \
  https://packages.gurobi.com/9.0/gurobi9.0.2_linux64.tar.gz
echo '6527581aef11c3e425c52993d108861ef53ec13971d9931861bf9c88d9d111f3  /tmp/gurobi9.0.2_linux64.tar.gz' \
  | sha256sum -c -
trap 'rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/* /tmp/gurobi9.0.2_linux64.tar.gz' EXIT
tar -C /opt -xf /tmp/gurobi9.0.2_linux64.tar.gz
echo '9d41a38c50ea58137a2100fda733ec0f47431059f9c4ebee4899ea1cdfe118f3  /opt/gurobi902/linux64/include/gurobi_c.h' \
  | sha256sum -c -

aws s3 cp --only-show-errors s3://drake-provisioning/gurobi/gurobi.lic \
  /opt/gurobi902/gurobi.lic
echo '85a76935617e809af43275fa4d7f7fc38182973c5756edde9b8db59ef65420cb  /opt/gurobi902/gurobi.lic' \
  | sha256sum -c -

chown -R root:root /opt/gurobi902
