#!/bin/bash

# Copyright (c) 2019, Massachusetts Institute of Technology.
# Copyright (c) 2019, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ -z "${WORKSPACE-}" ]]; then
  echo 'ERROR: This script must be run on a Jenkins node' >&2
  exit 1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo 'ERROR: This script must be run as root' >&2
  exit 2
fi

systemctl disable apt-daily.service
systemctl disable apt-daily.timer

echo 'APT::Acquire::Retries "4";' | tee /etc/apt/apt.conf.d/80-acquire-retries

export DEBIAN_FRONTEND=noninteractive

apt-get update --quiet --quiet
trap 'rm --force --recursive /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/*' EXIT

apt-get purge --assume-yes --autoremove --option Dpkg::Use-Pty=0 --quiet cron unattended-upgrades

apt-get install --assume-yes --no-install-recommends --option Dpkg::Use-Pty=0 --quiet \
  apt-transport-https \
  awscli \
  ca-certificates \
  git \
  gnupg \
  lsb-release \
  ntp \
  openjdk-8-jdk-headless \
  wget \
  xvfb

cat << 'EOF' > /lib/systemd/system/xvfb.service
[Unit]
After=network.target

[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset

[Install]
WantedBy=multi-user.target
EOF

systemctl --now enable /lib/systemd/system/xvfb.service

wget --no-verbose --output-document - https://apt.kitware.com/keys/kitware-archive-latest.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -
echo "deb https://apt.kitware.com/ubuntu/ $(lsb_release --codename --short) main" | tee /etc/apt/sources.list.d/kitware.list

apt-get update --quiet --quiet
apt-get install --assume-yes --no-install-recommends --option Dpkg::Use-Pty=0 --quiet \
  cmake \
  kitware-archive-keyring

apt-key --keyring /etc/apt/trusted.gpg del C1F34CDD40CD72DA

wget --no-verbose --output-document /tmp/gurobi8.0.1_linux64.tar.gz https://packages.gurobi.com/8.0/gurobi8.0.1_linux64.tar.gz
echo '28c028b8708869c27a93edc2769b645db4906dc7c80a4d283ed6db672b587478  /tmp/gurobi8.0.1_linux64.tar.gz' | shasum --algorithm 256 --check -
trap 'rm --force --recursive /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /tmp/gurobi8.0.1_linux64.tar.gz' EXIT
tar --extract --file /tmp/gurobi8.0.1_linux64.tar.gz --directory /opt
aws s3 cp --quiet s3://drake-provisioning/gurobi/gurobi.lic /opt/gurobi801/gurobi.lic
echo '85a76935617e809af43275fa4d7f7fc38182973c5756edde9b8db59ef65420cb  /opt/gurobi801/gurobi.lic' | shasum --algorithm 256 --check -
chown --recursive root:root /opt/gurobi801
