#!/bin/bash

set -euxo pipefail

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)

apt-get install -o APT::Acquire::Retries=4 -y --no-install-recommends locales

locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
