#!/bin/bash

# Copyright (c) 2020, Massachusetts Institute of Technology.
# Copyright (c) 2020, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

export DEBIAN_FRONTEND=noninteractive

debconf-set-selections << EOF
man-db man-db/auto-update boolean false
EOF

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)

apt-get install -o APT::Acquire::Retries=4 -y --no-install-recommends \
  lsb-release

echo "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-updates main restricted universe multiverse" \
  >> /etc/apt/sources.list

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)

apt-get dist-upgrade -o APT::Acquire::Retries=4 -y

apt-get install -o APT::Acquire::Retries=4 -y --no-install-recommends \
  ca-certificates \
  gnupg \
  wget

wget -nv -t4 -O- https://bazel.build/bazel-release.pub.gpg | apt-key add -

cp /var/cache/pbuilder/bindmount/bazel.list /etc/apt/sources.list.d

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)
