#!/bin/bash

set -euxo pipefail

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)

apt-get install -o APT::Acquire::Retries=4 -y --no-install-recommends \
  lsb-release

echo "deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ $(lsb_release -cs)-updates main restricted universe multiverse" \
  >> /etc/apt/sources.list

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)

apt-get dist-upgrade -o APT::Acquire::Retries=4 -y

apt-get install -o APT::Acquire::Retries=4 -y --no-install-recommends \
  ca-certificates \
  gnupg

apt-key adv --fetch-keys https://bazel.build/bazel-release.pub.gpg \
  || (sleep 15; apt-key adv --fetch-keys https://bazel.build/bazel-release.pub.gpg)

cp /var/cache/pbuilder/bindmount/bazel.list /etc/apt/sources.list.d

apt-get update -o APT::Acquire::Retries=4 \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4)
