#!/bin/bash

# Copyright (c) 2019, Massachusetts Institute of Technology.
# Copyright (c) 2019, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo 'ERROR: This script must be run using sudo -E or as root' >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

apt-get update -o APT::Acquire::Retries=4 -qq \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4 -qq)
trap 'set +x; rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*; set -x' EXIT

apt-get install --no-install-recommends -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
  cowbuilder \
  git \
  git-buildpackage \
  lintian \
  lsb-release \
  pristine-tar \
  xz-utils

git config --global tar.tar.xz.command 'xz -c'
git config --global user.email drake.jenkins.bot@gmail.com
git config --global user.name drake-jenkins-bot

if [[ -z "${SSH_PRIVATE_KEY_FILE:-}" ]]; then
  echo 'ERROR: Environment variable SSH_PRIVATE_KEY_FILE was NOT set' >&2
  exit 2
fi

mkdir -p /var/cache/pbuilder/bindmount /var/cache/pbuilder/hook.d

pushd "${BASH_SOURCE%/*}"

cp .bazelrc bazel.list git_ssh /var/cache/pbuilder/bindmount
cp .gbp.conf .pbuilderrc /home/ubuntu
cp A10-git-ssh A20-locale B10-autopkgtest D10-apt /var/cache/pbuilder/hook.d

popd

chown ubuntu:ubuntu /home/ubuntu/.gbp.conf /home/ubuntu/.pbuilderrc

chmod 0755 \
  /var/cache/pbuilder/hook.d/A10-git-ssh \
  /var/cache/pbuilder/hook.d/A20-locale \
  /var/cache/pbuilder/hook.d/B10-autopkgtest \
  /var/cache/pbuilder/hook.d/D10-apt

cp "${SSH_PRIVATE_KEY_FILE:-}" /var/cache/pbuilder/bindmount/id_rsa

export ARCH=amd64
export DIST=$(lsb_release -cs)
export GIT_PBUILDER_OPTIONS="--bindmounts /var/cache/pbuilder/bindmount --components 'main restricted universe multiverse' --hookdir /var/cache/pbuilder/hook.d --use-network yes" \

git-pbuilder create
