#!/usr/bin/env bash

# This script is intended for use by maintainers in the creation of provisioned
# images, not during regular CI workflows which run on every job. See README.md
# for usage details.

set -euxo pipefail

feedback () {
  echo -n $'\033[32m'
  echo "$0"
  echo -n $'\033[00m'
}

die () {
  echo >&2 "$@"
}

if sudo -n true &>/dev/null; then
  feedback "sudo password prompt already disabled."
else
  feedback "Disabling sudo password prompt..."
  readonly sudoers_file="/private/etc/sudoers.d/$(whoami)-no-sudo"
  echo "$(whoami) ALL=(ALL) NOPASSWD: ALL" | sudo tee "${sudoers_file}" \
    && sudo chmod 440 "${sudoers_file}"
fi

feedback "Installing Homebrew..."
if ! command -v brew &>/dev/null; then
  /bin/bash -c \
    "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

readonly brew_prefix="$(brew --prefix)"
if [ -z "${brew_prefix}" ]; then
  die "Empty Homebrew prefix; check your installation and re-run this script"
fi
feedback "Fixing Homebrew permissions..."
sudo chown -R $(whoami) "${brew_prefix}"

feedback "Running Homebrew post-installation steps..."
readonly brew_eval_command="eval \"\$(${brew_prefix} shellenv)\""
for shell_rc in ( "${HOME}/.zshrc" "${HOME}/.bashrc" ); do
  if [ -f "${shell_rc}" ]; then
    grep -qF "${brew_eval_command}" "${shell_rc}" || \
      echo "${brew_eval_command}" >> "${shell_rc}"
  fi
done

# N.B. Gurobi requires Rosetta 2 to run on ARM (despite providing a "universal2"
# pkg file). We should investigate whether this can be removed with future
# versions of Gurobi.
feedback "Installing Rosetta 2..."
sudo softwareupdate --install-rosetta --agree-to-license

feedback "Disabling automatic update downloads..."
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate \
  AutomaticDownload -boolean false

feedback "Disabling Spotlight indexing and filesystem logs..."
sudo mdutil -a -i off
readonly data_dir="/System/Volumes/Data/"
sudo rm -rf "$data_dir/.Spotlight*"
readonly never_index="$data_dir/.metadata_never_index"
sudo touch $never_index
sudo chmod 444 $never_index
readonly fseventsd_dir="$data_dir/.fseventsd"
sudo rm -rf $fseventsd_dir
sudo mkdir $fseventsd_dir
sudo touch "$fseventsd_dir/no_log"
sudo chmod 444 "$fseventsd_dir/no_log"

readonly restart_time="U 00:00:00"
feedback "Configuring regular restarts at $restart_time..."
sudo pmset repeat restart $restart_time
