#!/bin/zsh

# BSD 3-Clause License
#
# Copyright (c) 2019, Massachusetts Institute of Technology.
# Copyright (c) 2019, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -euxo pipefail

if [[ -z "${WORKSPACE-}" ]]; then
  echo 'ERROR: This script must be run on a Jenkins node' >&2
  exit 1
fi

if [[ "${EUID}" -eq 0 ]]; then
  echo 'ERROR: This script must NOT be run as root' >&2
  exit 2
fi

[[ -z "${TERM-}" ]] || export HOMEBREW_COLOR=1

export HOMEBREW_CASK_OPTS=--require-sha
export HOMEBREW_CURL_RETRIES=4
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

brew analytics off
brew update || (sleep 15; brew update)
# Update this version of pip as Drake updates its supported Python versions.
trap 'brew cleanup && pip3.14 cache purge && rm -rf "$(brew --cache)" "${HOME}/Library/Logs/Homebrew/*"' EXIT
brew upgrade

# Install Java, to be used for Jenkins. The version must be the same as the one
# used by Jenkins.
brew install --cask temurin@21

readonly gurobi_1203_pkg='/tmp/gurobi12.0.3_macos_universal2.pkg'
curl --retry 4 -o $gurobi_1203_pkg \
  https://packages.gurobi.com/12.0/$(basename $gurobi_1203_pkg)
echo "e1e771e9cf8aa7882b1cdc000be91c2b5fadd18f3fcdd00f2824dd207be09613  $gurobi_1203_pkg" \
  | sha256sum -c -
sudo /usr/sbin/installer -pkg $gurobi_1203_pkg -target /
