#!/bin/bash

# BSD 3-Clause License
#
# Copyright (c) 2024, Massachusetts Institute of Technology.
# Copyright (c) 2024, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script is intended for use by maintainers in the creation of provisioned
# images, not during regular CI workflows which run on every job. See README.md
# for usage details.

set -eu -o pipefail

cleanup () {
  rm -rf "${drake_root}"

  brew cleanup --prune=all
  rm -rf "$(brew --cache)"
  rm -rf "${HOME}/Library/Logs/Homebrew/*"

  # Update this version of pip as Drake updates its supported Python versions.
  pip3.14 cache purge
}

usage () {
  cat << EOF
Usage: $1 [-h|--help] [{--drake-sha SHA|--drake-pull PR [--merge]}]

Options:
  --help              Display this message and exit
  --drake-sha         Drake git SHA to use for provisioning
  --drake-pull PR     Drake pull request ID to use for provisioning
  --merge             Use the merge of the PR and master rather than the PR head
EOF
}

die () {
  echo >&2 "$@"
  exit 1
}

invalid_argument () {
  echo >&2 "Invalid command line argument: $@"
  usage "$0" >&2
  exit 1
}

install_gurobi () {
  local url="$1"
  shift
  readonly url

  local pkg_sha256="$1"
  shift
  readonly pkg_sha256

  local pkg_dest="/tmp/$(basename ${url})"
  readonly pkg_dest

  curl --retry 4 -o "${pkg_dest}" "${url}"
  echo "${pkg_sha256}  ${pkg_dest}" | sha256sum -c -
  sudo /usr/sbin/installer -pkg "${pkg_dest}" -target /
}

[[ "${EUID}" -ne 0 ]] || die 'This script must NOT be run as root.'

drake_sha=
drake_pull=
drake_pull_merge=0

while [ "${1:-}" != "" ]; do
  case "$1" in
    --drake-sha)
      shift
      if [[ -z "${1:-}" ]]; then
        invalid_argument '--drake-sha requires a SHA.'
      fi
      drake_sha="$1"
      ;;
    --drake-pull)
      shift
      if [[ -z "${1:-}" ]]; then
        invalid_argument '--drake-pull requires a PR ID.'
      fi
      drake_pull="$1"
      ;;
    --merge)
      drake_pull_merge=1
      ;;
    -h|--help)
      usage "$0"
      exit 0
      ;;
    *)
      invalid_argument "$1"
  esac
  shift
done

if [[ -n "${drake_sha}" && -n "${drake_pull}" ]]; then
  invalid_argument 'At most one of --drake-sha or --drake-pull may be given.'
fi

if [[ -z "${drake_pull}" && "${drake_pull_merge}" -eq 1 ]]; then
  invalid_argument '--merge can only be given with --drake-pull.'
fi

set -x

readonly setup_mac_dir="$(dirname "${BASH_SOURCE}")"
readonly drake_root="$(mktemp -d -t drake-ci-provisioning)"

trap 'cleanup' EXIT

[[ -z "${TERM-}" ]] || export HOMEBREW_COLOR=1

export HOMEBREW_CASK_OPTS=--require-sha
export HOMEBREW_CURL_RETRIES=4
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

brew analytics off
brew update || (sleep 15; brew update)
brew upgrade

install_gurobi \
  'https://packages.gurobi.com/13.0/gurobi13.0.1_macos_universal2.pkg' \
  '7175c242af47bb248ef9adb4993f0d907e755ff2712a18f6902fa878edfa9b97'

# Install Java, to be used for Jenkins. The version must be the same as the one
# used by Jenkins.
brew install --cask temurin@21

# Clone Drake, and optionally check out a particular branch.
git clone https://github.com/RobotLocomotion/drake.git \
  --depth 1 "${drake_root}"
drake_branch=
if [[ -n "${drake_sha}" ]]; then
  drake_branch="${drake_sha}"
elif [[ -n "${drake_pull}" ]]; then
  if [[ "${drake_pull_merge}" -eq 1 ]]; then
    drake_branch="pull/${drake_pull}/merge"
  else
    drake_branch="pull/${drake_pull}/head"
  fi
fi
if [[ -n "${drake_branch}" ]]; then
  git -C "${drake_root}" fetch origin "${drake_branch}" --depth 1
  git -C "${drake_root}" checkout FETCH_HEAD
fi

# Install Drake's prerequisites.
readonly drake_setup_script="${drake_root}/setup/mac/install_prereqs.sh"
if [[ ! -f "${drake_setup_script}" ]]; then
  die "drake setup script not found; expected: ${drake_setup_script}"
fi
# Use `--developer` to install the prereqs for building wheels.
"${drake_setup_script}" --developer
