#!/bin/bash

# BSD 3-Clause License
#
# Copyright (c) 2024, Massachusetts Institute of Technology.
# Copyright (c) 2024, Toyota Research Institute.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script is expected to only be used in the creation of provisioned images
# NOT during normal CI setup

set -euxo pipefail

readonly setup_mac_dir="$(dirname "${BASH_SOURCE}")"

# WORKSPACE=setup is a bypass that allows the script to run (which requires
# that it be defined, as Jenkins always does).
WORKSPACE=setup "${setup_mac_dir}/install_prereqs"

readonly drake_root="$(mktemp -d -t drake-ci-provisioning)"
trap "rm -rf '${drake_root}'" EXIT
git clone https://github.com/RobotLocomotion/drake.git \
    --depth 1 "${drake_root}"

readonly drake_setup_script="${drake_root}/setup/mac/install_prereqs.sh"
if [[ ! -f "${drake_setup_script}" ]]; then
  echo "drake setup script not found; expected: ${drake_setup_script}" >&2
  exit 1
fi
# Use `--developer` to install the prereqs for building wheels.
"${drake_setup_script}" --developer
