# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT PUSHING NIGHTLY RELEASE BRANCH BECAUSE CMAKE BUILD OR TEST WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: PUSHING NIGHTLY RELEASE BRANCH")

  set(GIT_FETCH_ARGS "fetch --no-tags --progress origin +refs/heads/nightly-release")
  separate_arguments(GIT_FETCH_ARGS_LIST UNIX_COMMAND "${GIT_FETCH_ARGS}")
  execute_process(COMMAND "${CTEST_GIT_COMMAND}" ${GIT_FETCH_ARGS_LIST}
    WORKING_DIRECTORY "${CTEST_SOURCE_DIRECTORY}"
    RESULT_VARIABLE DASHBOARD_GIT_FETCH_NIGHTLY_RELEASE_BRANCH_RESULT_VARIABLE)
  if(NOT DASHBOARD_GIT_FETCH_NIGHTLY_RELEASE_BRANCH_RESULT_VARIABLE EQUAL 0)
    append_step_status("PUSHING NIGHTLY RELEASE BRANCH (GIT FETCH)" UNSTABLE)
  endif()

  if(NOT DASHBOARD_UNSTABLE)
    set(GIT_PUSH_ARGS "push --progress origin HEAD:refs/heads/nightly-release")
    separate_arguments(GIT_PUSH_ARGS_LIST UNIX_COMMAND "${GIT_PUSH_ARGS}")
    execute_process(COMMAND "${CTEST_GIT_COMMAND}" ${GIT_PUSH_ARGS_LIST}
      WORKING_DIRECTORY "${CTEST_SOURCE_DIRECTORY}"
      RESULT_VARIABLE DASHBOARD_GIT_PUSH_NIGHTLY_RELEASE_BRANCH_RESULT_VARIABLE)
    if(NOT DASHBOARD_GIT_PUSH_NIGHTLY_RELEASE_BRANCH_RESULT_VARIABLE EQUAL 0)
      append_step_status("PUSHING NIGHTLY RELEASE BRANCH (GIT PUSH)" UNSTABLE)
    endif()
  endif()
endif()
