# -*- mode: cmake; -*-
# vi: set ft=cmake:

begin_stage(
  PROJECT_NAME "drake"
  BUILD_NAME "${DASHBOARD_JOB_NAME}")

ctest_update(SOURCE "${CTEST_SOURCE_DIRECTORY}"
  RETURN_VALUE DASHBOARD_UPDATE_RETURN_VALUE
  CAPTURE_CMAKE_ERROR DASHBOARD_UPDATE_CAPTURE_CMAKE_ERROR
  QUIET)
if(DASHBOARD_UPDATE_RETURN_VALUE EQUAL -1 OR DASHBOARD_UPDATE_CAPTURE_CMAKE_ERROR EQUAL -1)
  message(WARNING "*** CTest update step was not successful")
endif()

file(WRITE "${CTEST_BINARY_DIRECTORY}/CMakeCache.txt" "${CACHE_CONTENT}")

ctest_configure(BUILD "${CTEST_BINARY_DIRECTORY}"
  OPTIONS --warn-uninitialized
  SOURCE "${CTEST_SOURCE_DIRECTORY}"
  RETURN_VALUE DASHBOARD_CONFIGURE_RETURN_VALUE
  CAPTURE_CMAKE_ERROR DASHBOARD_CONFIGURE_CAPTURE_CMAKE_ERROR
  QUIET)

if(NOT DASHBOARD_CONFIGURE_RETURN_VALUE EQUAL 0 OR DASHBOARD_CONFIGURE_CAPTURE_CMAKE_ERROR EQUAL -1)
  append_step_status("CMAKE CONFIGURE" FAILURE)
endif()

ctest_read_custom_files("${CTEST_BINARY_DIRECTORY}")

ctest_build(BUILD "${CTEST_BINARY_DIRECTORY}"
  RETURN_VALUE DASHBOARD_BUILD_RETURN_VALUE
  CAPTURE_CMAKE_ERROR DASHBOARD_BUILD_CAPTURE_CMAKE_ERROR
  QUIET)

if(NOT DASHBOARD_BUILD_RETURN_VALUE EQUAL 0)
  append_step_status("CMAKE BUILD" FAILURE)
endif()

if(DASHBOARD_SUBMIT)
  ctest_submit(
    BUILD_ID DASHBOARD_CDASH_BUILD_ID
    RETRY_COUNT 4
    RETRY_DELAY 15
    RETURN_VALUE DASHBOARD_SUBMIT_RETURN_VALUE
    CAPTURE_CMAKE_ERROR DASHBOARD_SUBMIT_CAPTURE_CMAKE_ERROR
    QUIET)
  if(NOT DASHBOARD_SUBMIT_RETURN_VALUE EQUAL 0 OR DASHBOARD_SUBMIT_CAPTURE_CMAKE_ERROR EQUAL -1)
    message(WARNING "*** CTest submit step was not successful")
  endif()

  if(DASHBOARD_CDASH_BUILD_ID)
    message(STATUS "*** Submitted to CDash with build id ${DASHBOARD_CDASH_BUILD_ID}")
  endif()
endif()
