# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT UPLOADING PACKAGE ARCHIVE BECAUSE CMAKE BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: UPLOADING PACKAGE ARCHIVE")
  aws_upload("${DASHBOARD_WORKSPACE}/${DASHBOARD_PACKAGE_ARCHIVE_NAME}"
    "CMAKE PACKAGE ARCHIVE UPLOAD")
endif()
