# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT CREATING PACKAGE ARCHIVE BECAUSE CMAKE BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: CREATING PACKAGE ARCHIVE")
  if(NOT DASHBOARD_UNSTABLE)
    if(APPLE)
      set(DASHBOARD_PACKAGE_ARCHIVE_DISTRIBUTION mac-arm64)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
      set(DASHBOARD_PACKAGE_ARCHIVE_DISTRIBUTION "${DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME}-aarch64")
    else()
      set(DASHBOARD_PACKAGE_ARCHIVE_DISTRIBUTION "${DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME}")
    endif()

    set(DASHBOARD_PACKAGE_NAME "drake-${DASHBOARD_DRAKE_VERSION}")
    set(DASHBOARD_PACKAGE_ARCHIVE_NAME "${DASHBOARD_PACKAGE_NAME}-${DASHBOARD_PACKAGE_ARCHIVE_DISTRIBUTION}.tar.gz")

    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${DASHBOARD_WORKSPACE}/${DASHBOARD_PACKAGE_ARCHIVE_NAME}" drake
      WORKING_DIRECTORY /opt
      RESULT_VARIABLE TAR_RESULT_VARIABLE)
    if(NOT TAR_RESULT_VARIABLE EQUAL 0)
      append_step_status("CMAKE PACKAGE ARCHIVE CREATION" UNSTABLE)
    endif()
  endif()
endif()
