# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT INSTALLING BECAUSE CMAKE BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: INSTALLING DRAKE")
  ctest_build(BUILD "${CTEST_BINARY_DIRECTORY}"
    TARGET install APPEND
    RETURN_VALUE DASHBOARD_BUILD_RETURN_VALUE
    CAPTURE_CMAKE_ERROR DASHBOARD_BUILD_CAPTURE_CMAKE_ERROR
    QUIET)

  if(NOT DASHBOARD_BUILD_RETURN_VALUE EQUAL 0 OR DASHBOARD_BUILD_CAPTURE_CMAKE_ERROR EQUAL -1)
    append_step_status("CMAKE INSTALL" FAILURE)
  endif()

  if(DASHBOARD_SUBMIT)
    ctest_submit(
      BUILD_ID DASHBOARD_CDASH_BUILD_ID
      RETRY_COUNT 4
      RETRY_DELAY 15
      RETURN_VALUE DASHBOARD_SUBMIT_RETURN_VALUE
      CAPTURE_CMAKE_ERROR DASHBOARD_SUBMIT_CAPTURE_CMAKE_ERROR
      QUIET)
    if(NOT DASHBOARD_SUBMIT_RETURN_VALUE EQUAL 0 OR DASHBOARD_SUBMIT_CAPTURE_CMAKE_ERROR EQUAL -1)
      message(WARNING "*** CTest submit step was not successful")
    endif()
  endif()
endif()
