# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT UPLOADING DEBIAN ARCHIVE BECAUSE CMAKE BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: UPLOADING DEBIAN ARCHIVE")
  aws_upload("${DASHBOARD_WORKSPACE}/${DASHBOARD_DEBIAN_ARCHIVE_NAME}"
    "CMAKE DEBIAN ARCHIVE UPLOAD")
endif()
