set(DASHBOARD_SUPERBUILD_FAILURE OFF)

notice("CTest Status: DOWNLOADING GOOGLE_STYLEGUIDE")

# Set up parameters for dashboard submission
begin_stage(
  URL_NAME "Superbuild"
  PROJECT_NAME "drake-superbuild"
  BUILD_NAME "${DASHBOARD_BUILD_NAME}-download-cpplint")

# Set up the build and update the sources
ctest_update(SOURCE "${CTEST_SOURCE_DIRECTORY}"
  CAPTURE_CMAKE_ERROR DASHBOARD_SUPERBUILD_UPDATE_RETURN_VALUE QUIET)

# Configure superbuild
ctest_configure(BUILD "${CTEST_BINARY_DIRECTORY}"
  SOURCE "${CTEST_SOURCE_DIRECTORY}"
  CAPTURE_CMAKE_ERROR DASHBOARD_SUPERBUILD_CONFIGURE_RETURN_VALUE QUIET)
if(NOT DASHBOARD_SUPERBUILD_CONFIGURE_RETURN_VALUE EQUAL 0)
  append_step_status("CONFIGURE SUPERBUILD" FAILURE)
endif()

# Download google_styleguide (superbuild "build" step)
ctest_build(BUILD "${CTEST_BINARY_DIRECTORY}" APPEND
  TARGET "google_styleguide-update"
  CAPTURE_CMAKE_ERROR DASHBOARD_SUPERBUILD_DOWNLOAD_RETURN_VALUE QUIET)
if(NOT DASHBOARD_SUPERBUILD_DOWNLOAD_RETURN_VALUE EQUAL 0)
  append_step_status("DOWNLOAD SUPERBUILD" FAILURE)
endif()

# Submit the results
ctest_submit(RETRY_COUNT 4 RETRY_DELAY 15
  CAPTURE_CMAKE_ERROR DASHBOARD_SUPERBUILD_SUBMIT_RETURN_VALUE QUIET)

set(DASHBOARD_SUPERBUILD_FAILURE ${DASHBOARD_FAILURE})
