set(DASHBOARD_PACKAGES "")

macro(add_package NAME ENABLED)
  set(DASHBOARD_WITH_${NAME} ${ENABLED})
  list(APPEND DASHBOARD_PACKAGES ${NAME})
endmacro()

macro(enable_package NAME)
  set(DASHBOARD_WITH_${NAME} ON)
endmacro()

macro(disable_package NAME)
  set(DASHBOARD_WITH_${NAME} OFF)
endmacro()

add_package(BOT_CORE_LCMTYPES         ON)
add_package(BULLET                    ON)
add_package(DIRECTOR                  ON)
add_package(DRAKE                     ON)
add_package(EIGEN                     ON)
add_package(FMT                       ON)
add_package(GFLAGS                    ON)
add_package(GOOGLETEST                ON)
add_package(IPOPT                     ON)
add_package(LCM                       ON)
add_package(LIBBOT                    ON)
add_package(NLOPT                     ON)
add_package(PROTOBUF                  ON)
add_package(PYBIND11                  ON)
add_package(ROBOTLOCOMOTION_LCMTYPES  ON)
add_package(SPDLOG                    ON)
add_package(TINYOBJLOADER             ON)
add_package(YAML_CPP                  ON)

if(MATLAB)
    disable_package(DIRECTOR)
endif()

foreach(_package ${DASHBOARD_PACKAGES})
  cache_append(WITH_${_package} BOOL ${DASHBOARD_WITH_${_package}})
endforeach()
