set(DASHBOARD_INSTALL OFF)
set(DASHBOARD_TEST OFF)
set(DASHBOARD_CONFIGURATION_TYPE "Debug")

# Set extra compile flags
set(DASHBOARD_EXTRA_DEBUG_FLAGS "-O0")
prepend_flags(DASHBOARD_C_FLAGS ${DASHBOARD_EXTRA_DEBUG_FLAGS})
prepend_flags(DASHBOARD_CXX_FLAGS ${DASHBOARD_EXTRA_DEBUG_FLAGS})
prepend_flags(DASHBOARD_FORTRAN_FLAGS ${DASHBOARD_EXTRA_DEBUG_FLAGS})

# Set analyzer output directory and ensure it exists
set(DASHBOARD_CCC_ANALYZER_HTML "${DASHBOARD_WORKSPACE}/build/drake/html")
set(ENV{CCC_ANALYZER_HTML} "${DASHBOARD_CCC_ANALYZER_HTML}")
file(MAKE_DIRECTORY "${DASHBOARD_CCC_ANALYZER_HTML}")
