set(DASHBOARD_TEST_TIMEOUT_MULTIPLIER 1)

if(APPLE OR NOT DASHBOARD_WARM)
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 2")
endif()

if(DASHBOARD_CONFIGURATION_TYPE STREQUAL "Debug")
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 4")
endif()

if(COVERAGE)
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 4")
endif()

if(MEMCHECK)
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 4")
endif()

cache_append(TEST_TIMEOUT_MULTIPLIER STRING
  ${DASHBOARD_TEST_TIMEOUT_MULTIPLIER})

set(DASHBOARD_TEST_TIMEOUT 300)

math(EXPR DASHBOARD_TEST_TIMEOUT
  "${DASHBOARD_TEST_TIMEOUT} * ${DASHBOARD_TEST_TIMEOUT_MULTIPLIER}")

set(CTEST_TEST_TIMEOUT ${DASHBOARD_TEST_TIMEOUT})
