set(DASHBOARD_TEST_TIMEOUT_MULTIPLIER 1)

if(APPLE OR WIN32)
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 2")
endif()

if(DASHBOARD_CONFIGURATION_TYPE STREQUAL "Debug")
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 4")
endif()

if(COVERAGE)
  math(EXPR DASHBOARD_TEST_TIMEOUT_MULTIPLIER
    "${DASHBOARD_TEST_TIMEOUT_MULTIPLIER} * 2")
endif()

set(CACHE_TEST_TIMEOUT_MULTIPLIER
  "TEST_TIMEOUT_MULTIPLIER:STRING=${DASHBOARD_TEST_TIMEOUT_MULTIPLIER}")

# set(DASHBOARD_TEST_TIMEOUT 300)
#
# math(EXPR DASHBOARD_TEST_TIMEOUT
#   "${DASHBOARD_TEST_TIMEOUT} * ${DASHBOARD_TEST_TIMEOUT_MULTIPLIER}")
#
# set(CTEST_TEST_TIMEOUT ${DASHBOARD_TEST_TIMEOUT})

set(DASHBOARD_TEST_TIMEOUT 600)

if(DASHBOARD_CONFIGURATION_TYPE STREQUAL "Debug")
  set(DASHBOARD_TEST_TIMEOUT 2400)
endif()

if(MATLAB)
   math(EXPR DASHBOARD_TEST_TIMEOUT "${DASHBOARD_TEST_TIMEOUT} + 600")
endif()

set(CTEST_TEST_TIMEOUT ${DASHBOARD_TEST_TIMEOUT})
