#!/bin/bash

set -euxo pipefail

cleanup () {
  set +x
  rm -rf \
    /var/cache/apt/archives/*.deb \
    /var/cache/apt/archives/partial/*.deb \
    /var/cache/apt/*.bin \
    /var/lib/apt/lists/* \
    /var/log/apt/*
}

die () {
  echo >&2 "$@"
  exit 1
}

[[ "${EUID}" -eq 0 ]] || die 'This script must be run as root'

trap 'cleanup' EXIT

export DEBIAN_FRONTEND=noninteractive

apt-get update -o APT::Acquire::Retries=4 -qq \
  || (sleep 15; apt-get update -o APT::Acquire::Retries=4 -qq)

packages=$(cat "${BASH_SOURCE%/*}/packages.txt")
apt-get install --no-install-recommends \
  -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy \
  ${packages}

# Since v29, docker delegates container storage to containerd; ensure they both
# point to `/media/ephemeral0/...` so we don't overrun our small `/`.
readonly docker_data_root="/media/ephemeral0/docker"
readonly containerd_root="/media/ephemeral0/containerd"
mkdir -p ${docker_data_root} ${containerd_root}

systemctl stop docker.socket docker containerd || true
rm -rf /var/lib/docker /var/lib/containerd

mkdir -p /etc/docker
tee /etc/docker/daemon.json <<EOF
{
  "data-root": "${docker_data_root}"
}
EOF

mkdir -p /etc/containerd
tee /etc/containerd/config.toml <<EOF
root = "${containerd_root}"
EOF

systemctl daemon-reload
systemctl start containerd docker
docker info | grep "Docker Root Dir"
