# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT UPLOADING DOCUMENTATION ARCHIVE BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: UPLOADING DOCUMENTATION ARCHIVE")
  aws_upload("${DASHBOARD_DOCUMENTATION_ARCHIVE_NAME}"
    "DOCUMENTATION ARCHIVE UPLOAD")
endif()
