# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT BUILDING DOCUMENTATION BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: BUILDING DOCUMENTATION")

  set(BUILD_DOCUMENTATION_ARGS
    "${DASHBOARD_BAZEL_STARTUP_OPTIONS} run ${DASHBOARD_BAZEL_BUILD_OPTIONS} //doc:build -- --out_dir=${DASHBOARD_DOCUMENTATION_DIRECTORY}")
  separate_arguments(BUILD_DOCUMENTATION_ARGS_LIST UNIX_COMMAND "${BUILD_DOCUMENTATION_ARGS}")
  execute_process(COMMAND ${DASHBOARD_BAZEL_COMMAND} ${BUILD_DOCUMENTATION_ARGS_LIST}
    WORKING_DIRECTORY "${DASHBOARD_SOURCE_DIRECTORY}"
    RESULT_VARIABLE DASHBOARD_BUILD_DOCUMENTATION_RESULT_VARIABLE)
  if(NOT DASHBOARD_BUILD_DOCUMENTATION_RESULT_VARIABLE EQUAL 0)
    append_step_status("BUILDING DOCUMENTATION" UNSTABLE)
  endif()

  file(WRITE "${DASHBOARD_DOCUMENTATION_DIRECTORY}/CNAME" "drake.mit.edu")
  file(WRITE "${DASHBOARD_DOCUMENTATION_DIRECTORY}/googleb54a1809ac854371.html" "google-site-verification: googleb54a1809ac854371.html")
  file(TOUCH "${DASHBOARD_DOCUMENTATION_DIRECTORY}/.nojekyll")
endif()
