if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT PUSHING DOCKER IMAGE BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: PUSHING DOCKER IMAGE")

  set(AWS_S3_CP_DOCKER_CONFIG_JSON_ARGS "s3 cp s3://drake-encrypted/docker/config.json $ENV{HOME}/.docker/config.json")
  separate_arguments(AWS_S3_CP_DOCKER_CONFIG_JSON_ARGS_LIST UNIX_COMMAND "${AWS_S3_CP_DOCKER_CONFIG_JSON_ARGS}")
  execute_process(COMMAND "${DASHBOARD_AWS_COMMAND}" ${AWS_S3_CP_DOCKER_CONFIG_JSON_ARGS_LIST}
    RESULT_VARIABLE AWS_S3_CP_DOCKER_CONFIG_JSON_RESULT_VARIABLE
    COMMAND_ECHO STDERR)
  if(NOT AWS_S3_CP_DOCKER_CONFIG_JSON_RESULT_VARIABLE EQUAL 0)
    append_step_status("BAZEL PUSHING DOCKER IMAGE (AWS S3 CP DOCKER CONFIG.JSON)" UNSTABLE)
  endif()

  if(NOT DASHBOARD_UNSTABLE)
    execute_process(COMMAND "sudo" "${DASHBOARD_DOCKER_COMMAND}" "login"
      RESULT_VARIABLE DOCKER_LOGIN_RESULT_VARIABLE
      COMMAND_ECHO STDERR)
    if(NOT DOCKER_LOGIN_RESULT_VARIABLE EQUAL 0)
      append_step_status("BAZEL PUSHING DOCKER IMAGE (DOCKER LOGIN)" UNSTABLE)
    endif()
  endif()

  if(NOT DASHBOARD_UNSTABLE)
    set(DOCKER_PUSH_IMAGE_DATE_ARGS "push robotlocomotion/drake:${DATE}")
    separate_arguments(DOCKER_PUSH_IMAGE_DATE_ARGS_LIST UNIX_COMMAND "${DOCKER_PUSH_IMAGE_DATE_ARGS}")
    execute_process(COMMAND "sudo" "${DASHBOARD_DOCKER_COMMAND}" ${DOCKER_PUSH_IMAGE_DATE_ARGS_LIST}
      RESULT_VARIABLE DOCKER_PUSH_IMAGE_DATE_RESULT_VARIABLE
      COMMAND_ECHO STDERR)
    if(NOT DOCKER_PUSH_IMAGE_DATE_RESULT_VARIABLE EQUAL 0)
      append_step_status("BAZEL PUSHING DOCKER IMAGE (ROBOTLOCOMOTION/DRAKE:${DATE})" UNSTABLE)
    endif()
  endif()

  if(NOT DASHBOARD_UNSTABLE)
    set(DOCKER_PUSH_IMAGE_LATEST_ARGS "push robotlocomotion/drake:latest")
    separate_arguments(DOCKER_PUSH_IMAGE_LATEST_ARGS_LIST UNIX_COMMAND "${DOCKER_PUSH_IMAGE_LATEST_ARGS}")
    execute_process(COMMAND "sudo" "${DASHBOARD_DOCKER_COMMAND}" ${DOCKER_PUSH_IMAGE_LATEST_ARGS_LIST}
      RESULT_VARIABLE DOCKER_PUSH_IMAGE_LATEST_RESULT_VARIABLE
      COMMAND_ECHO STDERR)
    if(NOT DOCKER_PUSH_IMAGE_LATEST_RESULT_VARIABLE EQUAL 0)
      append_step_status("BAZEL PUSHING DOCKER IMAGE (ROBOTLOCOMOTION/DRAKE:LATEST)" UNSTABLE)
    endif()
  endif()
endif()
