# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT CREATING DOCUMENTATION ARCHIVE BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: CREATING DOCUMENTATION ARCHIVE")

  set(DASHBOARD_DOCUMENTATION_ARCHIVE_NAME
    "${DASHBOARD_WORKSPACE}/drake-doc-${DASHBOARD_DRAKE_VERSION}.tar.gz"
  )
  cmake_path(GET DASHBOARD_DOCUMENTATION_DIRECTORY
    PARENT_PATH DOC_WORKING_DIR
  )

  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf
    "${DASHBOARD_DOCUMENTATION_ARCHIVE_NAME}"
    "${DASHBOARD_DOCUMENTATION_DIRECTORY}"
    WORKING_DIRECTORY "${DOC_WORKING_DIR}"
    RESULT_VARIABLE TAR_RESULT_VARIABLE)
  if(NOT TAR_RESULT_VARIABLE EQUAL 0)
      append_step_status("DOCUMENTATION ARCHIVE CREATION" UNSTABLE)
  endif()
endif()
