if(DASHBOARD_FAILURE OR DASHBOARD_UNSTABLE)
  notice("CTest Status: NOT BUILDING DOCUMENTATION BECAUSE BAZEL BUILD WAS NOT SUCCESSFUL")
else()
  notice("CTest Status: BUILDING DOCUMENTATION")

  execute_process(COMMAND "${DASHBOARD_TOOLS_DIR}/build_documentation.bash"
    WORKING_DIRECTORY "${DASHBOARD_SOURCE_DIRECTORY}"
    RESULT_VARIABLE DASHBOARD_BUILD_DOCUMENTATION_RESULT_VARIABLE
    OUTPUT_VARIABLE DASHBOARD_BUILD_DOCUMENTATION_OUTPUT_VARIABLE
    ERROR_VARIABLE DASHBOARD_BUILD_DOCUMENTATION_OUTPUT_VARIABLE)
  message("${DASHBOARD_BUILD_DOCUMENTATION_OUTPUT_VARIABLE}")

  if(NOT DASHBOARD_BUILD_DOCUMENTATION_RESULT_VARIABLE EQUAL 0)
    append_step_status("BUILDING DOCUMENTATION" UNSTABLE)
  endif()
endif()
