# -*- mode: cmake; -*-
# vi: set ft=cmake:

if(APPLE)
  set(DASHBOARD_UNIX_DISTRIBUTION "Apple")
  find_program(DASHBOARD_SW_VERS_COMMAND NAMES "sw_vers")
  if(NOT DASHBOARD_SW_VERS_COMMAND)
    fatal("sw_vers was not found")
  endif()
  execute_process(COMMAND "${DASHBOARD_SW_VERS_COMMAND}" "-productVersion"
    RESULT_VARIABLE SW_VERS_RESULT_VARIABLE
    OUTPUT_VARIABLE SW_VERS_OUTPUT_VARIABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT SW_VERS_RESULT_VARIABLE EQUAL 0)
    fatal("unable to determine distribution release version")
  endif()
  if(SW_VERS_OUTPUT_VARIABLE MATCHES "([0-9]+)[.]([0-9]+)([.][0-9]+)?")
    set(DASHBOARD_UNIX_DISTRIBUTION_MAJOR_VERSION "${CMAKE_MATCH_1}")
    set(DASHBOARD_UNIX_DISTRIBUTION_MINOR_VERSION "${CMAKE_MATCH_2}")
  else()
    fatal("unable to determine distribution release version")
  endif()
  if(DASHBOARD_UNIX_DISTRIBUTION_MAJOR_VERSION EQUAL 15)
    set(DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME "sequoia")
  elseif(DASHBOARD_UNIX_DISTRIBUTION_MAJOR_VERSION EQUAL 26)
    set(DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME "tahoe")
  else()
    fatal("unable to determine distribution code name")
  endif()
  set(DASHBOARD_UNIX_DISTRIBUTION_VERSION "${DASHBOARD_UNIX_DISTRIBUTION_MAJOR_VERSION}")
else()
  cmake_host_system_information(RESULT DASHBOARD_UNIX_DISTRIBUTION QUERY DISTRIB_NAME)
  if(NOT DASHBOARD_UNIX_DISTRIBUTION)
    fatal("unable to determine distribution name")
  endif()
  cmake_host_system_information(
    RESULT DASHBOARD_UNIX_DISTRIBUTION_VERSION QUERY DISTRIB_VERSION_ID)
  if(NOT DASHBOARD_UNIX_DISTRIBUTION_VERSION)
    fatal("unable to determine distribution release version")
  endif()
  cmake_host_system_information(
    RESULT DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME QUERY DISTRIB_VERSION_CODENAME)
  if(NOT DASHBOARD_UNIX_DISTRIBUTION_CODE_NAME)
    fatal("unable to determine distribution code name")
  endif()
endif()
